// port-lint: source Windows/Win32/Foundation/mod.rs
@file:OptIn(kotlinx.cinterop.ExperimentalForeignApi::class)

package io.github.kotlinmania.windowssys.windows.win32.foundation

import platform.windows.GetLastError as winGetLastError

// Upstream line 6 in Windows/Win32/Foundation/mod.rs:
//
//   windows_link::link!("kernel32.dll" "system"
//       fn GetLastError() -> WIN32_ERROR);
//
// Returns the calling thread's last-error code value. Direct wrapper
// around `platform.windows.GetLastError` (kernel32.dll), generated by
// Kotlin/Native cinterop from the MinGW-w64 Windows SDK headers.

public fun GetLastError(): WIN32_ERROR = winGetLastError()
