// port-lint: source windows-sys/src/Windows/Win32/System/Threading/mod.rs
package io.github.kotlinmania.windowssys.windows.win32.system.threading

// Upstream process access rights and protection level constants.

public const val PROCESS_ALL_ACCESS: PROCESS_ACCESS_RIGHTS = 2097151u
public const val PROCESS_CREATE_PROCESS: PROCESS_ACCESS_RIGHTS = 128u
public const val PROCESS_CREATE_THREAD: PROCESS_ACCESS_RIGHTS = 2u
public const val PROCESS_DELETE: PROCESS_ACCESS_RIGHTS = 65536u
public const val PROCESS_DUP_HANDLE: PROCESS_ACCESS_RIGHTS = 64u
public const val PROCESS_QUERY_INFORMATION: PROCESS_ACCESS_RIGHTS = 1024u
public const val PROCESS_QUERY_LIMITED_INFORMATION: PROCESS_ACCESS_RIGHTS = 4096u
public const val PROCESS_READ_CONTROL: PROCESS_ACCESS_RIGHTS = 131072u
public const val PROCESS_SET_INFORMATION: PROCESS_ACCESS_RIGHTS = 512u
public const val PROCESS_SET_LIMITED_INFORMATION: PROCESS_ACCESS_RIGHTS = 8192u
public const val PROCESS_SET_QUOTA: PROCESS_ACCESS_RIGHTS = 256u
public const val PROCESS_SET_SESSIONID: PROCESS_ACCESS_RIGHTS = 4u
public const val PROCESS_STANDARD_RIGHTS_REQUIRED: PROCESS_ACCESS_RIGHTS = 983040u
public const val PROCESS_SUSPEND_RESUME: PROCESS_ACCESS_RIGHTS = 2048u
public const val PROCESS_SYNCHRONIZE: PROCESS_ACCESS_RIGHTS = 1048576u
public const val PROCESS_TERMINATE: PROCESS_ACCESS_RIGHTS = 1u
public const val PROCESS_VM_OPERATION: PROCESS_ACCESS_RIGHTS = 8u
public const val PROCESS_VM_READ: PROCESS_ACCESS_RIGHTS = 16u
public const val PROCESS_VM_WRITE: PROCESS_ACCESS_RIGHTS = 32u
public const val PROCESS_WRITE_DAC: PROCESS_ACCESS_RIGHTS = 262144u
public const val PROCESS_WRITE_OWNER: PROCESS_ACCESS_RIGHTS = 524288u

// PROTECTION_LEVEL constants
public const val PROTECTION_LEVEL_ANTIMALWARE_LIGHT: PROCESS_PROTECTION_LEVEL = 3u
public const val PROTECTION_LEVEL_AUTHENTICODE: PROCESS_PROTECTION_LEVEL = 7u
public const val PROTECTION_LEVEL_CODEGEN_LIGHT: PROCESS_PROTECTION_LEVEL = 6u
public const val PROTECTION_LEVEL_LSA_LIGHT: PROCESS_PROTECTION_LEVEL = 4u
public const val PROTECTION_LEVEL_NONE: PROCESS_PROTECTION_LEVEL = 4294967294u
public const val PROTECTION_LEVEL_PPL_APP: PROCESS_PROTECTION_LEVEL = 8u
public const val PROTECTION_LEVEL_WINDOWS: PROCESS_PROTECTION_LEVEL = 1u
public const val PROTECTION_LEVEL_WINDOWS_LIGHT: PROCESS_PROTECTION_LEVEL = 2u
public const val PROTECTION_LEVEL_WINTCB: PROCESS_PROTECTION_LEVEL = 5u
public const val PROTECTION_LEVEL_WINTCB_LIGHT: PROCESS_PROTECTION_LEVEL = 0u
