// port-lint: source Windows/Win32/System/Threading/mod.rs
package io.github.kotlinmania.windowssys.windows.win32.system.threading

// Upstream process creation flags, priority classes, and related
// constants — all typed as PROCESS_CREATION_FLAGS (u32 -> UInt).

public const val ABOVE_NORMAL_PRIORITY_CLASS: PROCESS_CREATION_FLAGS = 32768u
public const val BELOW_NORMAL_PRIORITY_CLASS: PROCESS_CREATION_FLAGS = 16384u
public const val CREATE_BREAKAWAY_FROM_JOB: PROCESS_CREATION_FLAGS = 16777216u
public const val CREATE_DEFAULT_ERROR_MODE: PROCESS_CREATION_FLAGS = 67108864u
public const val CREATE_FORCEDOS: PROCESS_CREATION_FLAGS = 8192u
public const val CREATE_IGNORE_SYSTEM_DEFAULT: PROCESS_CREATION_FLAGS = 2147483648u
public const val CREATE_NEW_CONSOLE: PROCESS_CREATION_FLAGS = 16u
public const val CREATE_NEW_PROCESS_GROUP: PROCESS_CREATION_FLAGS = 512u
public const val CREATE_NO_WINDOW: PROCESS_CREATION_FLAGS = 134217728u
public const val CREATE_PRESERVE_CODE_AUTHZ_LEVEL: PROCESS_CREATION_FLAGS = 33554432u
public const val CREATE_PROTECTED_PROCESS: PROCESS_CREATION_FLAGS = 262144u
public const val CREATE_SECURE_PROCESS: PROCESS_CREATION_FLAGS = 4194304u
public const val CREATE_SEPARATE_WOW_VDM: PROCESS_CREATION_FLAGS = 2048u
public const val CREATE_SHARED_WOW_VDM: PROCESS_CREATION_FLAGS = 4096u
public const val CREATE_SUSPENDED: PROCESS_CREATION_FLAGS = 4u
public const val CREATE_UNICODE_ENVIRONMENT: PROCESS_CREATION_FLAGS = 1024u
public const val DEBUG_ONLY_THIS_PROCESS: PROCESS_CREATION_FLAGS = 2u
public const val DEBUG_PROCESS: PROCESS_CREATION_FLAGS = 1u
public const val DETACHED_PROCESS: PROCESS_CREATION_FLAGS = 8u
public const val EXTENDED_STARTUPINFO_PRESENT: PROCESS_CREATION_FLAGS = 524288u
public const val HIGH_PRIORITY_CLASS: PROCESS_CREATION_FLAGS = 128u
public const val IDLE_PRIORITY_CLASS: PROCESS_CREATION_FLAGS = 64u
public const val INHERIT_CALLER_PRIORITY: PROCESS_CREATION_FLAGS = 131072u
public const val INHERIT_PARENT_AFFINITY: PROCESS_CREATION_FLAGS = 65536u
public const val NORMAL_PRIORITY_CLASS: PROCESS_CREATION_FLAGS = 32u
public const val PROCESS_MODE_BACKGROUND_BEGIN: PROCESS_CREATION_FLAGS = 1048576u
public const val PROCESS_MODE_BACKGROUND_END: PROCESS_CREATION_FLAGS = 2097152u
public const val PROFILE_KERNEL: PROCESS_CREATION_FLAGS = 536870912u
public const val PROFILE_SERVER: PROCESS_CREATION_FLAGS = 1073741824u
public const val PROFILE_USER: PROCESS_CREATION_FLAGS = 268435456u
public const val REALTIME_PRIORITY_CLASS: PROCESS_CREATION_FLAGS = 256u

// CREATE_EVENT constants
public const val CREATE_EVENT_INITIAL_SET: CREATE_EVENT = 2u
public const val CREATE_EVENT_MANUAL_RESET: CREATE_EVENT = 1u

// CREATE_PROCESS_LOGON_FLAGS constants
public const val LOGON_NETCREDENTIALS_ONLY: CREATE_PROCESS_LOGON_FLAGS = 2u
public const val LOGON_WITH_PROFILE: CREATE_PROCESS_LOGON_FLAGS = 1u

// CREATE_MUTEX / CREATE_WAITABLE_TIMER constants
public const val CREATE_MUTEX_INITIAL_OWNER: UInt = 1u
public const val CREATE_WAITABLE_TIMER_HIGH_RESOLUTION: UInt = 2u
public const val CREATE_WAITABLE_TIMER_MANUAL_RESET: UInt = 1u

// AVRT_PRIORITY constants
public const val AVRT_PRIORITY_CRITICAL: AVRT_PRIORITY = 2
public const val AVRT_PRIORITY_HIGH: AVRT_PRIORITY = 1
public const val AVRT_PRIORITY_LOW: AVRT_PRIORITY = -1
public const val AVRT_PRIORITY_NORMAL: AVRT_PRIORITY = 0
public const val AVRT_PRIORITY_VERYLOW: AVRT_PRIORITY = -2

// GET_GUI_RESOURCES_FLAGS constants
public const val GR_GDIOBJECTS: GET_GUI_RESOURCES_FLAGS = 0u
public const val GR_GDIOBJECTS_PEAK: GET_GUI_RESOURCES_FLAGS = 2u
public const val GR_GLOBAL: GET_GUI_RESOURCES_FLAGS = 4294967294u
public const val GR_USEROBJECTS: GET_GUI_RESOURCES_FLAGS = 1u
public const val GR_USEROBJECTS_PEAK: GET_GUI_RESOURCES_FLAGS = 4u

// PROCESS_DEP_FLAGS constants
public const val PROCESS_DEP_DISABLE_ATL_THUNK_EMULATION: PROCESS_DEP_FLAGS = 2u
public const val PROCESS_DEP_ENABLE: PROCESS_DEP_FLAGS = 1u
public const val PROCESS_DEP_NONE: PROCESS_DEP_FLAGS = 0u

// PROCESS_AFFINITY_AUTO_UPDATE_FLAGS constants
public const val PROCESS_AFFINITY_DISABLE_AUTO_UPDATE: PROCESS_AFFINITY_AUTO_UPDATE_FLAGS = 0u
public const val PROCESS_AFFINITY_ENABLE_AUTO_UPDATE: PROCESS_AFFINITY_AUTO_UPDATE_FLAGS = 1u

// PROCESS_NAME_FORMAT constants
public const val PROCESS_NAME_NATIVE: PROCESS_NAME_FORMAT = 1u
public const val PROCESS_NAME_WIN32: PROCESS_NAME_FORMAT = 0u

// POWER_REQUEST_CONTEXT_FLAGS constants
public const val POWER_REQUEST_CONTEXT_DETAILED_STRING: POWER_REQUEST_CONTEXT_FLAGS = 2u
public const val POWER_REQUEST_CONTEXT_SIMPLE_STRING: POWER_REQUEST_CONTEXT_FLAGS = 1u

// QUEUE_USER_APC_FLAGS constants
public const val QUEUE_USER_APC_CALLBACK_DATA_CONTEXT: QUEUE_USER_APC_FLAGS = 65536
public const val QUEUE_USER_APC_FLAGS_NONE: QUEUE_USER_APC_FLAGS = 0
public const val QUEUE_USER_APC_FLAGS_SPECIAL_USER_APC: QUEUE_USER_APC_FLAGS = 1

// RTWQ_WORKQUEUE_TYPE constants
public const val RTWQ_MULTITHREADED_WORKQUEUE: RTWQ_WORKQUEUE_TYPE = 2
public const val RTWQ_STANDARD_WORKQUEUE: RTWQ_WORKQUEUE_TYPE = 0
public const val RTWQ_WINDOW_WORKQUEUE: RTWQ_WORKQUEUE_TYPE = 1

// WORKER_THREAD_FLAGS constants
public const val WT_EXECUTEDEFAULT: WORKER_THREAD_FLAGS = 0u
public const val WT_EXECUTEINIOTHREAD: WORKER_THREAD_FLAGS = 1u
public const val WT_EXECUTEINPERSISTENTTHREAD: WORKER_THREAD_FLAGS = 128u
public const val WT_EXECUTEINTIMERTHREAD: WORKER_THREAD_FLAGS = 32u
public const val WT_EXECUTEINWAITTHREAD: WORKER_THREAD_FLAGS = 4u
public const val WT_EXECUTELONGFUNCTION: WORKER_THREAD_FLAGS = 16u
public const val WT_EXECUTEONLYONCE: WORKER_THREAD_FLAGS = 8u
public const val WT_TRANSFER_IMPERSONATION: WORKER_THREAD_FLAGS = 256u
