// port-lint: source windows-sys/src/Windows/Win32/System/Threading/mod.rs
package io.github.kotlinmania.windowssys.windows.win32.system.threading

// Upstream synchronization access rights constants.

public const val EVENT_ALL_ACCESS: SYNCHRONIZATION_ACCESS_RIGHTS = 2031619u
public const val EVENT_MODIFY_STATE: SYNCHRONIZATION_ACCESS_RIGHTS = 2u
public const val MUTEX_ALL_ACCESS: SYNCHRONIZATION_ACCESS_RIGHTS = 2031617u
public const val MUTEX_MODIFY_STATE: SYNCHRONIZATION_ACCESS_RIGHTS = 1u
public const val SEMAPHORE_ALL_ACCESS: SYNCHRONIZATION_ACCESS_RIGHTS = 2031619u
public const val SEMAPHORE_MODIFY_STATE: SYNCHRONIZATION_ACCESS_RIGHTS = 2u
public const val TIMER_ALL_ACCESS: SYNCHRONIZATION_ACCESS_RIGHTS = 2031619u
public const val TIMER_MODIFY_STATE: SYNCHRONIZATION_ACCESS_RIGHTS = 2u
public const val TIMER_QUERY_STATE: SYNCHRONIZATION_ACCESS_RIGHTS = 1u
public const val SYNCHRONIZATION_DELETE: SYNCHRONIZATION_ACCESS_RIGHTS = 65536u
public const val SYNCHRONIZATION_READ_CONTROL: SYNCHRONIZATION_ACCESS_RIGHTS = 131072u
public const val SYNCHRONIZATION_SYNCHRONIZE: SYNCHRONIZATION_ACCESS_RIGHTS = 1048576u
public const val SYNCHRONIZATION_WRITE_DAC: SYNCHRONIZATION_ACCESS_RIGHTS = 262144u
public const val SYNCHRONIZATION_WRITE_OWNER: SYNCHRONIZATION_ACCESS_RIGHTS = 524288u

// SYNCHRONIZATION_BARRIER flags
public const val SYNCHRONIZATION_BARRIER_FLAGS_BLOCK_ONLY: UInt = 2u
public const val SYNCHRONIZATION_BARRIER_FLAGS_NO_DELETE: UInt = 4u
public const val SYNCHRONIZATION_BARRIER_FLAGS_SPIN_ONLY: UInt = 1u
