// port-lint: source windows-sys/src/Windows/Win32/System/Threading/mod.rs
package io.github.kotlinmania.windowssys.windows.win32.system.threading

// Upstream standalone constants that don't belong to a specific
// type-alias group.

public const val ALL_PROCESSOR_GROUPS: UShort = 65535u
public const val CONDITION_VARIABLE_LOCKMODE_SHARED: UInt = 1u
public const val FLS_OUT_OF_INDEXES: UInt = 4294967295u
public const val INFINITE: UInt = 4294967295u
public const val INIT_ONCE_ASYNC: UInt = 2u
public const val INIT_ONCE_CHECK_ONLY: UInt = 1u
public const val INIT_ONCE_CTX_RESERVED_BITS: UInt = 2u
public const val INIT_ONCE_INIT_FAILED: UInt = 4u
public const val PRIVATE_NAMESPACE_FLAG_DESTROY: UInt = 1u
public const val RTL_CRITICAL_SECTION_ALL_FLAG_BITS: UInt = 4278190080u
public const val RTL_CRITICAL_SECTION_DEBUG_FLAG_STATIC_INIT: UInt = 1u
public const val RTL_CRITICAL_SECTION_FLAG_DYNAMIC_SPIN: UInt = 33554432u
public const val RTL_CRITICAL_SECTION_FLAG_FORCE_DEBUG_INFO: UInt = 268435456u
public const val RTL_CRITICAL_SECTION_FLAG_NO_DEBUG_INFO: UInt = 16777216u
public const val RTL_CRITICAL_SECTION_FLAG_RESOURCE_TYPE: UInt = 134217728u
public const val RTL_CRITICAL_SECTION_FLAG_STATIC_INIT: UInt = 67108864u
public const val STACK_SIZE_PARAM_IS_A_RESERVATION: THREAD_CREATION_FLAGS = 65536u
public const val TLS_OUT_OF_INDEXES: UInt = 4294967295u

// STARTUPINFOW_FLAGS constants
public const val STARTF_FORCEOFFFEEDBACK: STARTUPINFOW_FLAGS = 128u
public const val STARTF_FORCEONFEEDBACK: STARTUPINFOW_FLAGS = 64u
public const val STARTF_PREVENTPINNING: STARTUPINFOW_FLAGS = 8192u
public const val STARTF_RUNFULLSCREEN: STARTUPINFOW_FLAGS = 32u
public const val STARTF_TITLEISAPPID: STARTUPINFOW_FLAGS = 4096u
public const val STARTF_TITLEISLINKNAME: STARTUPINFOW_FLAGS = 2048u
public const val STARTF_UNTRUSTEDSOURCE: STARTUPINFOW_FLAGS = 32768u
public const val STARTF_USECOUNTCHARS: STARTUPINFOW_FLAGS = 8u
public const val STARTF_USEFILLATTRIBUTE: STARTUPINFOW_FLAGS = 16u
public const val STARTF_USEHOTKEY: STARTUPINFOW_FLAGS = 512u
public const val STARTF_USEPOSITION: STARTUPINFOW_FLAGS = 4u
public const val STARTF_USESHOWWINDOW: STARTUPINFOW_FLAGS = 1u
public const val STARTF_USESIZE: STARTUPINFOW_FLAGS = 2u
public const val STARTF_USESTDHANDLES: STARTUPINFOW_FLAGS = 256u

// MEMORY_PRIORITY constants
public const val MEMORY_PRIORITY_BELOW_NORMAL: MEMORY_PRIORITY = 4u
public const val MEMORY_PRIORITY_LOW: MEMORY_PRIORITY = 2u
public const val MEMORY_PRIORITY_MEDIUM: MEMORY_PRIORITY = 3u
public const val MEMORY_PRIORITY_NORMAL: MEMORY_PRIORITY = 5u
public const val MEMORY_PRIORITY_VERY_LOW: MEMORY_PRIORITY = 1u
