// port-lint: source Windows/Win32/System/Environment/mod.rs
package io.github.kotlinmania.windowssys.windows.win32.system.environment

public const val ENCLAVE_FLAG_DYNAMIC_DEBUG_ACTIVE: UInt = 4u
public const val ENCLAVE_FLAG_DYNAMIC_DEBUG_ENABLED: UInt = 2u
public const val ENCLAVE_FLAG_FULL_DEBUG_ENABLED: UInt = 1u

public const val ENCLAVE_IDENTITY_POLICY_SEAL_EXACT_CODE: ENCLAVE_SEALING_IDENTITY_POLICY = 1
public const val ENCLAVE_IDENTITY_POLICY_SEAL_INVALID: ENCLAVE_SEALING_IDENTITY_POLICY = 0
public const val ENCLAVE_IDENTITY_POLICY_SEAL_SAME_AUTHOR: ENCLAVE_SEALING_IDENTITY_POLICY = 5
public const val ENCLAVE_IDENTITY_POLICY_SEAL_SAME_FAMILY: ENCLAVE_SEALING_IDENTITY_POLICY = 4
public const val ENCLAVE_IDENTITY_POLICY_SEAL_SAME_IMAGE: ENCLAVE_SEALING_IDENTITY_POLICY = 3
public const val ENCLAVE_IDENTITY_POLICY_SEAL_SAME_PRIMARY_CODE: ENCLAVE_SEALING_IDENTITY_POLICY = 2

public const val ENCLAVE_REPORT_DATA_LENGTH: UInt = 64u
public const val ENCLAVE_RUNTIME_POLICY_ALLOW_DYNAMIC_DEBUG: UInt = 2u
public const val ENCLAVE_RUNTIME_POLICY_ALLOW_FULL_DEBUG: UInt = 1u
public const val ENCLAVE_UNSEAL_FLAG_STALE_KEY: UInt = 1u
public const val ENCLAVE_VBS_BASIC_KEY_FLAG_DEBUG_KEY: UInt = 8u
public const val ENCLAVE_VBS_BASIC_KEY_FLAG_FAMILY_ID: UInt = 2u
public const val ENCLAVE_VBS_BASIC_KEY_FLAG_IMAGE_ID: UInt = 4u
public const val ENCLAVE_VBS_BASIC_KEY_FLAG_MEASUREMENT: UInt = 1u

public const val VBS_ENCLAVE_REPORT_PKG_HEADER_VERSION_CURRENT: UInt = 1u
public const val VBS_ENCLAVE_REPORT_SIGNATURE_SCHEME_SHA256_RSA_PSS_SHA256: UInt = 1u
public const val VBS_ENCLAVE_REPORT_VERSION_CURRENT: UInt = 1u
public const val VBS_ENCLAVE_VARDATA_INVALID: UInt = 0u
public const val VBS_ENCLAVE_VARDATA_MODULE: UInt = 1u
